// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package msg

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MQLoginChallenge struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Bytes_A          []byte  `protobuf:"bytes,2,req,name=bytes_A" json:"bytes_A,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MQLoginChallenge) Reset()         { *m = MQLoginChallenge{} }
func (m *MQLoginChallenge) String() string { return proto.CompactTextString(m) }
func (*MQLoginChallenge) ProtoMessage()    {}

func (m *MQLoginChallenge) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MQLoginChallenge) GetBytes_A() []byte {
	if m != nil {
		return m.Bytes_A
	}
	return nil
}

type MRLoginChallenge struct {
	Salt             []byte `protobuf:"bytes,1,req,name=salt" json:"salt,omitempty"`
	Bytes_B          []byte `protobuf:"bytes,2,req,name=bytes_B" json:"bytes_B,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MRLoginChallenge) Reset()         { *m = MRLoginChallenge{} }
func (m *MRLoginChallenge) String() string { return proto.CompactTextString(m) }
func (*MRLoginChallenge) ProtoMessage()    {}

func (m *MRLoginChallenge) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *MRLoginChallenge) GetBytes_B() []byte {
	if m != nil {
		return m.Bytes_B
	}
	return nil
}

type MQLoginVerify struct {
	Bytes_M          []byte `protobuf:"bytes,1,req,name=bytes_M" json:"bytes_M,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MQLoginVerify) Reset()         { *m = MQLoginVerify{} }
func (m *MQLoginVerify) String() string { return proto.CompactTextString(m) }
func (*MQLoginVerify) ProtoMessage()    {}

func (m *MQLoginVerify) GetBytes_M() []byte {
	if m != nil {
		return m.Bytes_M
	}
	return nil
}

type MRLoginVerify struct {
	Bytes_HAMK       []byte `protobuf:"bytes,1,req,name=bytes_HAMK" json:"bytes_HAMK,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MRLoginVerify) Reset()         { *m = MRLoginVerify{} }
func (m *MRLoginVerify) String() string { return proto.CompactTextString(m) }
func (*MRLoginVerify) ProtoMessage()    {}

func (m *MRLoginVerify) GetBytes_HAMK() []byte {
	if m != nil {
		return m.Bytes_HAMK
	}
	return nil
}

type MRLoginResult struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MRLoginResult) Reset()         { *m = MRLoginResult{} }
func (m *MRLoginResult) String() string { return proto.CompactTextString(m) }
func (*MRLoginResult) ProtoMessage()    {}

func (m *MRLoginResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
}
