// Code generated by protoc-gen-go.
// source: role.proto
// DO NOT EDIT!

package msg

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MRoleSimple struct {
	Guid             *uint32 `protobuf:"varint,1,req,name=guid" json:"guid,omitempty"`
	Occupation       *uint32 `protobuf:"varint,2,req,name=occupation" json:"occupation,omitempty"`
	Gender           *uint32 `protobuf:"varint,3,req,name=gender" json:"gender,omitempty"`
	Hp               *uint32 `protobuf:"varint,4,req,name=hp" json:"hp,omitempty"`
	Mp               *uint32 `protobuf:"varint,5,req,name=mp" json:"mp,omitempty"`
	Xp               *uint32 `protobuf:"varint,6,req,name=xp" json:"xp,omitempty"`
	Mapid            *uint32 `protobuf:"varint,7,req,name=mapid" json:"mapid,omitempty"`
	Mapx             *uint32 `protobuf:"varint,8,req,name=mapx" json:"mapx,omitempty"`
	Mapy             *uint32 `protobuf:"varint,9,req,name=mapy" json:"mapy,omitempty"`
	Level            *uint32 `protobuf:"varint,10,req,name=level" json:"level,omitempty"`
	Name             *string `protobuf:"bytes,11,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MRoleSimple) Reset()         { *m = MRoleSimple{} }
func (m *MRoleSimple) String() string { return proto.CompactTextString(m) }
func (*MRoleSimple) ProtoMessage()    {}

func (m *MRoleSimple) GetGuid() uint32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *MRoleSimple) GetOccupation() uint32 {
	if m != nil && m.Occupation != nil {
		return *m.Occupation
	}
	return 0
}

func (m *MRoleSimple) GetGender() uint32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *MRoleSimple) GetHp() uint32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *MRoleSimple) GetMp() uint32 {
	if m != nil && m.Mp != nil {
		return *m.Mp
	}
	return 0
}

func (m *MRoleSimple) GetXp() uint32 {
	if m != nil && m.Xp != nil {
		return *m.Xp
	}
	return 0
}

func (m *MRoleSimple) GetMapid() uint32 {
	if m != nil && m.Mapid != nil {
		return *m.Mapid
	}
	return 0
}

func (m *MRoleSimple) GetMapx() uint32 {
	if m != nil && m.Mapx != nil {
		return *m.Mapx
	}
	return 0
}

func (m *MRoleSimple) GetMapy() uint32 {
	if m != nil && m.Mapy != nil {
		return *m.Mapy
	}
	return 0
}

func (m *MRoleSimple) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MRoleSimple) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type MRRoleSimple struct {
	TargetId         *uint32      `protobuf:"varint,1,req,name=target_id" json:"target_id,omitempty"`
	Data             *MRoleSimple `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MRRoleSimple) Reset()         { *m = MRRoleSimple{} }
func (m *MRRoleSimple) String() string { return proto.CompactTextString(m) }
func (*MRRoleSimple) ProtoMessage()    {}

func (m *MRRoleSimple) GetTargetId() uint32 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

func (m *MRRoleSimple) GetData() *MRoleSimple {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
